-- TrickList.hs
module TrickList where

tricks100 :: [String]
tricks100 =
  [ "kickflip"
  , "heelflip"
  , "varial kickflip"
  , "varial heelflip"
  , "tre flip"
  , "inward heelflip"
  , "hardflip"
  , "double kickflip"
  , "double heelflip"
  , "laser flip"
  , "bigspin flip"
  , "bigspin"
  , "bigflip"
  , "impossible"
  , "hospital flip"
  , "pressure flip"
  , "ollie"
  , "switch ollie"
  , "nollie"
  , "fakie ollie"
  , "fakie bigspin"
  , "fakie kickflip"
  , "fakie heelflip"
  , "fakie tre flip"
  , "fakie varial flip"
  , "fakie inward heel"
  , "fakie bigflip"
  , "switch flip"
  , "switch heel"
  , "switch tre flip"
  , "switch bigspin"
  , "switch varial flip"
  , "switch bigflip"
  , "nollie flip"
  , "nollie heel"
  , "nollie bigspin"
  , "nollie tre flip"
  , "nollie inward heel"
  , "nollie bigflip"
  , "shuvit"
  , "pop shuvit"
  , "fs shuvit"
  , "fs pop shuvit"
  , "fakie shuvit"
  , "fakie pop shuvit"
  , "switch shuvit"
  , "switch pop shuvit"
  , "nollie shuvit"
  , "nollie pop shuvit"
  , "manual"
  , "nose manual"
  , "switch manual"
  , "fakie manual"
  , "nollie manual"
  , "manual to flip out"
  , "nose manual nollie flip out"
  , "manual shuvit out"
  , "ollie to manual"
  , "flip to manual"
  , "fs 180"
  , "bs 180"
  , "half cab"
  , "full cab"
  , "nollie 180"
  , "switch 180"
  , "fakie fs 180"
  , "fakie bs 180"
  , "fs flip"
  , "bs flip"
  , "nollie fs flip"
  , "nollie bs flip"
  , "switch fs flip"
  , "switch bs flip"
  , "fakie fs flip"
  , "fakie bs flip"
  , "bs revert"
  , "fs revert"
  , "bs powerslide"
  , "fs powerslide"
  , "kickflip underflip"
  , "heelflip body varial"
  , "kickflip body varial"
  , "no comply"
  , "boneless"
  , "boneless 180"
  , "firecracker"
  , "caveman"
  , "darkslide"
  , "casper flip"
  , "sex change"
  , "ollie north"
  , "nollie big heel"
  , "switch inward heel"
  , "switch hardflip"
  , "bs bigspin"
  , "fs bigspin"
  , "fs 360"
  , "bs 360"
  , "fs 360 shuvit"
  , "bs 360 shuvit"
  ]
